# Generated by Django 2.2.2 on 2023-06-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('rating', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('metacritic_rating', models.PositiveIntegerField()),
                ('runtime', models.CharField(max_length=20)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
